<?php
require('./Controllers/adminExercisesUnorderedSentencesController.php');

require ('connect.php');

include('index.phtml');

include('adminPanel.php');

?>

<div class="wrapper">
    <h2>Gestion phrases déstructurées</h2>
    <ul>
        <li><a href="#addExercice">Ajouter des phrases</a></li>
        <li><a href="#exercisesList">Catalogue de phrases</a></li>
    </ul>

    <section id="exercisesList">
        <table>
            <thead>
                <th>N°</th>
                <th>Phrases</th>
                <th>Actions</th>
            </thead>
            <tbody>
                <?php foreach($admin->sentences as $sentence) : ?>
                    <tr>
                        <td class="exerciseId"><?= $sentence['exerciseId'] ?></td>
                        <td class="exerciseSentence"><?= $sentence['sentence'] ?></td>
                        <td>
                            <form action="./Controllers/adminUpdateExercise.php" method="post">
                                <button><i class="fa fa-pencil"></i></button>
                                <input type="hidden" name="exerciseName" value="unorderedSentences">
                                <input type="hidden" name="exerciseId" value="<?= $sentence['exerciseId'] ?>">
                                <input type="hidden" name="exerciseContent" value="<?= $sentence['sentence'] ?>">
                            </form>
                            <form action="./Controllers/adminDeleteExercise.php" method="post">
                                <button><i class="fa fa-times"></i></button>
                                <input type="hidden" name="exerciseName" value="unorderedSentences">
                                <input type="hidden" name="exerciseId" value="<?= $sentence['exerciseId'] ?>">
                            </form>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <section id="addExercice">
        <form action="Controllers/adminAddExercise.php" method="post">
            <label for="newSentence">Phrase à ajouter</label>
            <input type="text" name="newSentence" id="newSentence">
            <input type="hidden" name="exerciseName" value="unorderedSentences">

            <input type="submit" id="submitButton" value="Sauvegarder">
        </form>
    </section>
</div>


<script src="./assets/js/adminExercisesUnorderedSentences.js" type="text/javascript"></script>
<?php

include('footer.php');
?>
