<?php
require('./Controllers/adminExercisesUnorderedSentencesController.php');

require ('connect.php');

include('index.phtml');

include('adminPanel.php');

?>

<div class="wrapper">
    <h2>Gestion phrases déstructurées</h2>
    <ul>
        <li><a href="#addSentences">Ajouter des phrases</a></li>
        <li><a href="#existingSentences">Catalogue de phrases</a></li>
    </ul>

    <section id="#existingSentences">
        <table>
            <thead>
                <th>N°</th>
                <th>Phrases</th>
                <th>Actions</th>
            </thead>
            <tbody>
                <?php foreach($admin->sentences as $sentence) : ?>
                    <tr>
                        <td><?= $sentence['exerciseId'] ?></td>
                        <td><?= $sentence['sentence'] ?></td>
                        <td>
                            <i class="fa fa-pencil"></i>
                            <i class="fa fa-times"></i>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <section id="#addSentences">
        <form action="./Controllers/adminAddExercise.php" method="POST">
            <label for="newSentence">Phrase à ajouter</label>
            <input type="text" name="newSentence" id="newSentence">
            <input type="hidden" name="exerciseName" value="unorderedSentences">
        </form>
    </section>
</div>



<?php

include('footer.php');
?>
