<?php
require('./Controllers/unorderedSentencesController.php');

require ('connect.php');

include('index.phtml');

include('adminPanel.php');
?>

<div class="wrapper">
    <h2>Gestion des exercices</h2>


    <ul>
        <li>
            <a href="adminExercisesUnorderedSentences.phtml">Phrases déstructurées</a>
        </li>
        <li>
            <a href="adminExercisesMadLibs.phtml">Textes à trous</a>
        </li>
    </ul>

</div>



<?php

include('footer.php');
?>
