<?php
require('connect.php');
?>
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Projet fin d'année</title>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles/normalize.css">
    <link rel="stylesheet" href="styles/style.css">

</head>
<body>
    <header>
        <ul>
            <li>
                <a href="unorderedSentences.phtml">Phrases déstructurées</a>
            </li>
            <li>
                <a href="admin.phtml">Administration</a>
            </li>
        </ul>
    </header>
</body>


