<?php
require ('config.php');
require('./connect.php');
if(isset($_SESSION)) {
    var_dump($_SESSION);
}
?>
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Projet fin d'année</title>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/styles/normalize.css">
    <link rel="stylesheet" href="assets/styles/style.css">

</head>
<body>
    <header>
        <ul>
            <li>
                <a href="unorderedSentences.phtml">Phrases déstructurées</a>
            </li>
            <li>
                <a href="madLibs.phtml">Textes à trous</a>
            </li>
            <?php if(isset($_SESSION['connectedUser']) && ($_SESSION['connectedUser']['role'] == 'teacher' || $_SESSION['connectedUser']['role'] == 'admin')): ?>
            <li>
                <a href="admin.phtml">Administration</a>
            </li>
            <?php endif; ?>
        </ul>

        <?php if(!isset($_SESSION['connectedUser'])) : ?>
            <a href="userConnection.phtml">Connectez vous</a>
        <?php endif; ?>

        <?php if(isset($_SESSION['connectedUser'])) : ?>
            <a href="./Controllers/userLogOutController.php">Déconnexion</a>
        <?php endif; ?>
    </header>

    <main>


