<?php

require('index.phtml');
require('./Controllers/madLibsController.php');

?>


<form class="exercise" action="madLibsResult.phtml" method="post">

    <?php foreach ($madLibs->display as $exercise) : ?>
        <fieldset class="exercise_question">
            <div class="words gameButton">
                <?php foreach ($exercise['fillingWords'] as $word) : ?>
                    <div class="word gameButton"><?= $word ?></div>
                <?php endforeach; ?>
            </div>

            <?php foreach ($exercise['wording'] as $wording) : ?>

                <?= $wording ?>

            <?php endforeach; ?>
        </fieldset>


    <?php endforeach; ?>
    <input type="submit" value="Valider">
</form>

<script type="text/javascript" src="assets/js/madLibs.js"></script>


