<?php
 require('index.phtml');

 ?>


<div class="connectionModule">

    <form action="./Controllers/userConnectionController.php" method="post">

        <label for="username">Nom d'utilisateur</label>
        <input type="text" name="username" placeholder="Votre nom d'utilisateur" id="username">

        <label for="password">Mot de passe</label>
        <input type="password" name="password" placeholder="Votre mot de passe">

        <input type="submit" value="Log-in">


    </form>

</div>

<div class="subscriptionModule">
    <form action="./Controllers/userSubscriptionController.php" method="post">
        <label for="username">Nom d'utilisateur</label>
        <input type="text" name="username" placeholder="Votre nom d'utilisateur" id="username">

        <label for="email">Nom d'utilisateur</label>
        <input type="text" name="email" placeholder="Votre adresse email" id="email">

        <label for="password">Mot de passe</label>
        <input type="password" name="password" placeholder="Votre mot de passe">

        <input type="submit" value="Inscription">
    </form>
</div>
