
<div class="splitscreen">
    <div class="splitscreenLeft">
        <section>
            <h3>
                Qui suis-je ?
            </h3>
            <article>
                <h4>Une passionnée des langues</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis consequuntur dicta, impedit
                    odit quidem sequi sunt ut veniam voluptates! A aliquam consequatur doloremque illo impedit non nulla
                    quis saepe.</p>
            </article>
            <article>
                <h4>Expérience des langues</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis consequuntur dicta, impedit
                    odit quidem sequi sunt ut veniam voluptates! A aliquam consequatur doloremque illo impedit non nulla
                    quis saepe.</p>
            </article>
            <article>
                <h4>Expérience des langues</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad blanditiis consequuntur dicta, impedit
                    odit quidem sequi sunt ut veniam voluptates! A aliquam consequatur doloremque illo impedit non nulla
                    quis saepe.</p>
            </article>

        </section>

        <a href="mailto:#">
            <button>Ecrivez-moi</button>
        </a>

    </div>
    <div class="splitscreenRight imgContainer">
        <figure>
            <img src="./assets/images/pexels-tove-liu-3937645.jpg" alt="Milan, Galleria Vittorio Emanuele II">

            <figcaption>
                Milan, par <strong><a
                            href="https://www.pexels.com/@tove-liu-2127454?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Tove
                        Liu</a></strong>, sur <strong><a
                            href="https://www.pexels.com/photo/a-mall-in-glass-covered-arcade-3937645/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
            </figcaption>
        </figure>
    </div>
</div>