<?php


?>

    <div class="banner">
        <h2>Kikou</h2>
    </div>

    <div class="splitscreen">
        <div class="splitscreenLeft imgContainer">
            <figure>
                <img src="./assets/images/pexels-maegan-white-981687.jpg" alt="Florence, vue sur les toits">

                <figcaption>
                    Florence, par <strong><a
                                href="https://www.pexels.com/@maegan-white-363530?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Maegan
                            White</a></strong>, sur <strong><a
                                href="https://www.pexels.com/photo/brown-concrete-buildings-at-daytime-981687/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
                </figcaption>
            </figure>
        </div>
        <div class="splitscreenRight">

            <section>
                <h3>À qui s'adressent ces cours?</h3>
                <article>
                    <h4>Des cours personnalisés</h4>
                    <p>
                        Je propose des cours par Skype à tous les élèves qui souhaitent apprendre l'italien avec une
                        progression personnalisée.
                        Les cours s'adaptent au niveau et à la progression de chaque élève.
                        Avec des exercices choisis en fonction de vos besoins et centres d'intérêts, vous serez sûr de
                        progresser correctement.
                    </p>
                </article>
                <article>
                    <h4>Allier la pratique à la découverte de la culture</h4>
                    <p>
                        La culture d'un pays est un élément indissociable de sa langue. Au travers des cours, nous
                        découvrirons ensemble la culture.
                        Qu'il s'agisse de la pizza, des scooters, ou des secrets cachés de mon pays, je vous invite à
                        vous ouvrir à ses charmes.
                    </p>
                </article>
            </section>
            <button>Interessé? Contactez-moi</button>
        </div>
    </div>

    <div class="splitscreen">
        <div class="splitscreenLeft">
            <section>
                <h3>
                    Qui suis-je ?
                </h3>
                <article>
                    <h4>Une passion</h4>
                </article>
                <article>
                    <h4>Expérience des langues</h4>
                </article>

            </section>

            <button>Ecrivez-moi</button>

        </div>
        <div class="splitscreenRight imgContainer">
            <figure>
                <img src="./assets/images/pexels-tove-liu-3937645.jpg" alt="Milan, Galleria Vittorio Emanuele II">

                <figcaption>
                    Milan, par <strong><a
                                href="https://www.pexels.com/@tove-liu-2127454?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Tove
                            Liu</a></strong>, sur <strong><a
                                href="https://www.pexels.com/photo/a-mall-in-glass-covered-arcade-3937645/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
                </figcaption>
            </figure>
        </div>
    </div>

    <script type="text/javascript" src="assets/js/aboutDisplay.js"></script>
<?php

require('footer.php');

?>