<div class="index banner">
    <h1>Lasciatemi Parlare !</h1>
    <h2>Cours particuliers d'italien en ligne</h2>
</div>


<div class="splitscreen">
    <div class="splitscreenLeft textContainer">
        <section>
            <h3>Des cours d'italien en ligne</h3>
            <article>
                <h4>Apprenez de n'importe où</h4>
                <p>Il suffit d'une connexion internet, d'un ordinateur ou d'une tablette avec une webcam pour pouvoir
                    commencer à suivre les cours de Lasciatemi Parlare</p>
            </article>
            <article>
                <h4>Des cours particuliers</h4>
                <p>Les cours sont toujours particuliers. Vous bénéficiez ainsi d'une heure avec le professeur qui va
                    répondre à vos questions, et proposer des enseignements adaptés à votre but, vos besoins.</p>
            </article>
            <article>
                <h4>Des formules flexibles</h4>
                <p>Les horaires de vos cours peuvent être adaptés pour être en accord avec votre emploi du temps. Si
                    vous partez en vacances, pas de problème, les cours ne sont pas décomptés s'ils ne sont pas
                    donnés.</p>
            </article>

        </section>


    </div>
    <div class="splitscreenRight imgContainer">
        <figure>
            <img src="./assets/images/pexels-tove-liu-3937645.jpg" alt="Milan, Galleria Vittorio Emanuele II">

            <figcaption>
                Milan, par <strong><a
                            href="https://www.pexels.com/@tove-liu-2127454?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Tove
                        Liu</a></strong>, sur <strong><a
                            href="https://www.pexels.com/photo/a-mall-in-glass-covered-arcade-3937645/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
            </figcaption>
        </figure>
    </div>
</div>


<div class="splitscreen">

    <div class="splitscreenRight textContainer">

        <section>
            <h3>À qui s'adressent ces cours?</h3>
            <article>
                <h4>Des cours personnalisés</h4>
                <p>
                    Je propose des cours par Skype à tous les élèves qui souhaitent apprendre l'italien avec une
                    progression personnalisée.
                    Les cours s'adaptent au niveau et à la progression de chaque élève.
                    Avec des exercices choisis en fonction de vos besoins et centres d'intérêts, vous serez sûr de
                    progresser correctement.
                </p>
            </article>
            <article>
                <h4>Allier la pratique à la découverte de la culture</h4>
                <p>
                    La culture d'un pays est un élément indissociable de sa langue. Au travers des cours, nous
                    découvrirons ensemble la culture.
                    Qu'il s'agisse de la pizza, des scooters, ou des secrets cachés de mon pays, je vous invite à
                    vous ouvrir à ses charmes.
                </p>
            </article>
        </section>
        <a href="mailto:#">
            <button>Intéressé? Contactez-moi</button>
        </a>
    </div>
    <div class="splitscreenLeft imgContainer">
        <figure>
            <img src="./assets/images/pexels-maegan-white-981687.jpg" alt="Florence, vue sur les toits">

            <figcaption>
                Florence, par <strong><a
                            href="https://www.pexels.com/@maegan-white-363530?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Maegan
                        White</a></strong>, sur <strong><a
                            href="https://www.pexels.com/photo/brown-concrete-buildings-at-daytime-981687/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
            </figcaption>
        </figure>
    </div>
</div>

<div class="splitscreen">
    <div class="splitscreenLeft textContainer">
        <section>
            <h3>Et combien ça coûte?</h3>
            <article>
                <h4>Un cours d'essai gratuit !</h4>
                <p>Vous n'êtes pas certain que cela soit adapté pour vous? Vous pouvez réserver un cours d'essai de 30
                    minutes, totalement gratuit. Ce cours permet de prendre contact avec l'un de nos professeurs,
                    d'évaluer vos besoins, et ne vous engage à rien.</p>
            </article>
            <article>
                <h4>Un tarif dégressif</h4>
                <p>Un cours d'une heure coute 40 €. Cependant, il existe des formules dans lesquelles le prix est
                    dégressif en fonction du nombre de cours achetés d'un coup :</p>
                <div class="pricesBox">
                    <div class="priceBox">
                        <h5 class="hourNumber">
                            Cours à l'unité
                        </h5>
                        <h6>Prix horaire</h6>
                        <div class="hourlyRate">
                            40 €
                        </div>
                    </div>
                    <div class="priceBox">
                        <h5 class="hourNumber">
                            Pack de 5 cours
                        </h5>
                        <h6>Prix horaire</h6>
                        <div class="hourlyRate">
                            36 €
                        </div>
                        <h6>Réduction</h6>
                        <div class="discount">
                            10 %
                        </div>
                        <h6>Prix du pack</h6>
                        <div class="totalCost">
                            180 €
                            <div class="originalCost">200 €</div>
                        </div>
                    </div>
                    <div class="priceBox">
                        <h5 class="hourNumber">
                            Pack de 10 cours
                        </h5>
                        <h6>Prix horaire</h6>
                        <div class="hourlyRate">
                            34 €
                        </div>
                        <h6>Réduction</h6>
                        <div class="discount">
                            15 %
                        </div>
                        <h6>Prix du pack</h6>
                        <div class="totalCost">
                            340 €
                            <div class="originalCost">400 €</div>
                        </div>
                    </div>
                    <div class="priceBox">
                        <h5 class="hourNumber">
                            Pack de 15 cours
                        </h5>
                        <h6>Prix horaire</h6>
                        <div class="hourlyRate">
                            32 €
                        </div>
                        <h6>Réduction</h6>
                        <div class="discount">
                            20 %
                        </div>
                        <h6>Prix du pack</h6>
                        <div class="totalCost">
                            480 €
                            <div class="originalCost">600 €</div>
                        </div>
                    </div>
                </div>
            </article>
        </section>
        <a href="mailto:#">
            <button>Réservez votre cours d'essai !</button>
        </a>


    </div>
    <div class="splitscreenRight imgContainer">
        <figure>
            <img src="./assets/images/pexels-julius-silver-753639.jpg" alt="Rome">

            <figcaption>
                Rome, par <strong><a
                            href="https://www.pexels.com/@julius-silver-240301?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Julius
                        Silver</a></strong>, sur <strong><a
                            href="https://www.pexels.com/photo/photography-of-lighted-bridge-753639/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong>
            </figcaption>
        </figure>
    </div>
</div>


