<?php

?>


<div class="wrapper">

    <form class="exercise" action="madLibsResult" method="post">

        <?php foreach ($data as $exercise) : ?>
            <fieldset class="exercise_question">
                <div class="words gameButton">
                    <?php foreach ($exercise['fillingWords'] as $word) : ?>
                        <div class="word gameButton"><?= $word ?></div>
                    <?php endforeach; ?>
                </div>
                <div class="wording">
                    <?php foreach ($exercise['wording'] as $wording) : ?>

                        <?= $wording ?>

                    <?php endforeach; ?>
                </div>
            </fieldset>


        <?php endforeach; ?>
        <input type="submit" value="Valider">
    </form>
</div>

<script type="text/javascript" src="../assets/js/madLibs.js"></script>
<script type="text/javascript" src="../assets/js/exerciseDisplay.js"></script>
<script type="text/javascript" src="../assets/js/formValidation.js"></script>


