<div class="banner">
    <h2>Textes à trous</h2>
</div>
<div class="fullscreen">
    <section class="rule">
        <p>Complétez les phrases avec les mots proposés.</p>
    </section>

    <form class="exercise" action="madLibsResult" method="post">

        <?php foreach ($data as $exercise) : ?>
            <fieldset class="exercise_question">
                <div class="exercise_answerElements">

                    <?php foreach ($exercise['fillingWords'] as $word) : ?>
                        <div class="word gameButton"><?= $word ?></div>
                    <?php endforeach; ?>

                </div>
                <div class="wording">
                    <?php foreach ($exercise['wording'] as $wording) : ?>

                        <?= $wording ?>

                    <?php endforeach; ?>
                </div>
            </fieldset>


        <?php endforeach; ?>
        <input type="submit" value="Valider">
    </form>
</div>


