<h1>Correction</h1>

<table>
    <thead>
    <tr>
        <td>Votre réponse</td>
        <td>Correction</td>
        <td>Résultat</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['correction'] as $sentence) : ?>

        <tr class="<?php if ($sentence['rating'] == 'Faux') {
            echo 'failure';
        }
        ?>">
            <td><?= $sentence['userAnswer'] ?></td>
            <td><?= $sentence['correctAnswer'] ?></td>
            <td><?= $sentence['rating'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="note">
    Note : <?= $data['note'] ?>
</div>