<?php
require('index.phtml');
require('./Controllers/unorderedSentencesController.php');

?>


    <div class="wrapper">
        <h2>Examen</h2>

        <section class="rule">
            <p>Remettez les phrases dans l'ordre</p>
        </section>

        <form action="unorderedSentencesResult.php" class="exercise" method="post"/>

        <?php foreach ($unorderedSentences as $index => $sentences) : ?>

            <fieldset class="exercise_question">

                <div class="exercise_answerElements">
                    <?php foreach ($sentences['sentence'] as $word) : ?>

                        <div class="word gameButton"><?= $word ?></div>
                    <?php endforeach; ?>
                </div>

                <label for="anwser">Votre réponse : </label>
                <input type="text" class="answer" name="<?= $index ?>" id="answer_<?= $index ?>">


            </fieldset>

        <?php endforeach; ?>
    <fieldset>
        <input type="submit" value="Valider">
    </fieldset>

    </form>
</div>

    <script type="text/javascript" src="assets/js/unorderedSentences.js"></script>
    <script type="text/javascript" src="assets/js/exerciseDisplay.js"></script>
<?php

include('footer.php');

?>