<div class="banner">
    <h2>Correction</h2>
</div>
<div class="note">
    Note : <?= $data['note'] ?>
</div>
<div class="fullscreen">
    <table>
        <thead>
        <tr>
            <td>Votre réponse</td>
            <td>Correction</td>
            <td>Résultat</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data['correction'] as $sentence) : ?>

            <tr class="<?php if ($sentence['rating'] == 'Faux') {
                echo 'failure';
            }
            ?>">
                <td><?= $sentence['userAnswer'] ?></td>
                <td><?= $sentence['correctAnswer'] ?></td>
                <td><?= $sentence['rating'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


</div>