<div class="banner">
    <h2>Phrases déstructurées</h2>
</div>
<div class="fullscreen">


    <section class="rule">
        <p>Remettez les phrases dans l'ordre</p>
    </section>

    <form action="unorderedSentencesResult" class="exercise" method="post"/>

    <?php foreach ($data as $index => $sentences) : ?>

        <fieldset class="exercise_question">

            <div class="exercise_answerElements">
                <?php foreach ($sentences['sentence'] as $word) : ?>

                    <div class="word gameButton"><?= $word ?></div>
                <?php endforeach; ?>
            </div>

            <label for="anwser_<?= $index ?>">Votre réponse : </label>
            <input type="text" class="answer" name="<?= $index ?>" id="answer_<?= $index ?>">


        </fieldset>

    <?php endforeach; ?>

    <input type="submit" value="Valider">


    </form>
</div>
