<?php


require('./Controllers/adminUpdateExercise.php');
?>

<h2>Modification d'exercise</h2>

<div class="wrapper">
    <section>
        <div>Type d'exercice: <?= $display['name'] ?></div>
        <div>ID : <?= $display['id'] ?></div>
    </section>

    <form action="Controllers/adminUpdateExerciseSave.php" method="post">
        <label for="exerciseContent">Exercise à modifier</label>
        <input type="text" id="exerciseContent" name="exerciseContent" value="<?= $display['content'] ?>">
        <input type="hidden" name="exerciseId" value="<?= $display['id'] ?>">
        <input type="hidden" name="exerciseName" value="<?= $display['dbTableName'] ?>">

        <input type="submit" id="submitButton" value="Enregistrer">
    </form>
</div>