<?php if (isset($_SESSION['error']) && $_SESSION['error'] !== []) : ?>
    <div class="displayError">
        <?= $_SESSION['error'] ?>
    </div>
<?php endif; ?>


<div class="connectionModule">

    <form action="UserConnectionModule" method="post">

        <label for="username">Nom d'utilisateur</label>
        <input type="text" name="username" placeholder="Votre nom d'utilisateur" id="username">

        <label for="password">Mot de passe</label>
        <input type="password" name="password" placeholder="Votre mot de passe">

        <input type="submit" value="Log-in">


    </form>

</div>

<div class="subscriptionModule">
    <form action="userSubscription" method="post">
        <label for="username">Nom d'utilisateur</label>
        <input type="text" name="username" placeholder="Votre nom d'utilisateur" id="username">

        <label for="email">Email</label>
        <input type="text" name="email" placeholder="Votre adresse email" id="email">

        <label for="password">Mot de passe</label>
        <input type="password" name="password" placeholder="Votre mot de passe">

        <input type="submit" value="Inscription">
    </form>
</div>
