<?php
require('./Controllers/unorderedSentencesController.php');

require ('connect.php');

include('index.phtml');
?>

<section class="wrapper">
    <h2>Titre</h2>
    <?php if(isset($_SESSION['error'])) { echo $_SESSION['error']; }; ?>
    <div class="rule">
        <p>Remettez les phrases dans l'ordre</p>
    </div>
    <?php var_dump($_SESSION) ?>
    <div class="round">
        <p>Nombre d'essais : <?= $_SESSION['roundCount'] ?>
        </p>
    </div>
    <div class="exercise">
        <div class="exercise_question">
        <?php foreach ($unorderedSentences as $word) : ?>
            <div class="word gameButton"><?= $word ?></div>
        <?php endforeach; ?>
        </div>
            <div class="exercise_box">
                <form action="sendAnswer.php" class="exercise_question" method="post" />
                    <label for="anwser">Votre réponse : </label>
                    <input type="text" name="answer" id="answer">

                    <input type="submit" value="Valider">
                </form>
            </div>

    </div>
</section>